### ISSUE TITLE
Chouquette module

### ISSUE THREAD

**Issue by cyb3rd4d** [RiperFr/Security-ActiveDirectoryBundle#1]
Hello!

I need a module plugged to your bundle to log the user credentials. This may be usefull to send chouquettes!

**Comment by ztec** [comment]
How do you you whant to proceed ? Just let a window open ?

**Comment by ztec** [comment]
In debug mode I have this  :

``` php
[2012-11-02 12:49:16] security.INFO: User "ztec" has been authenticated successfully [] []
```

Maybe it can be use for what you want ?

**Comment by tekool** [comment]
Don't you think the whole process can be automatized? Is there any Microsoft Exchange Symphony 2 plug-in to automatically:
1. Store the user password into a secured database (it is really important to secure it for privacy concerns, I hope you understand this point).
2. Automatically log-in to Exchange with the plug-in.
3. Send a pre-formatted e-mail including a random animated image (it is really important for the image to be animated) and a subject/text to announce the next chouquette day incoming.

Note that you'll have to be sure not to send an e-mail for the same day, I think this will be the harder part of the work.

PS: Just don't forget to unit test the chouquettes on each release.

**Comment by ztec** [comment]
OMG

**Comment by cyb3rd4d** [comment]
@tekool You are Evil!

**Comment by tekool** [comment]
Hum? You don't want to implement a functionnality that community is asking you to do so…for let say years? You just closed the issue without no more explanation? Not a professionnal behavior!

**Comment by ztec** [comment]
For all Chouquettes related feature, I suggest you take a look at https://github.com/chouquette/chouquette_test .

You may find your "bonheur", or may not. 

Hasta la vista, baby ! :-)
