### ISSUE TITLE
login exceptions message

### ISSUE THREAD

**Issue by Zhuull** [RiperFr/Security-ActiveDirectoryBundle#14]
Hi,

I don't know why but when the login form throw an exception, I get a message like "ztec.security.active_directory.wrong_credential" or  "ztec.security.active_directory.invalid_user" instead of "Bad credentials" or something like this. I am the only one ?

**Comment by ztec** [comment]
What is you symfony2 version and your language (in symfony2) ?

**Comment by Zhuull** [comment]
I'm using Symfony 2.4.4 (in french)

**Comment by ztec** [comment]
Do you have this config in your config.yml ? 

```
 framework:
      translator: { fallback: en }
```
