### ISSUE TITLE
Access to LDAP after authentication

### ISSUE THREAD

**Issue by oleksandr-kaleniuk** [RiperFr/Security-ActiveDirectoryBundle#15]
Hi
I use your bundle for authentication with Active Directory and it works perfectly. But now I need to implement search in LDAP for users and unfortunately I didn't find solution for this. So as I understand I have to authenticate user again before search or use previous connection. 
Is it possible to get access to authenticated AD connection in controller?

**Comment by ztec** [comment]
For now, It's not possible. Maybe a repository can be made to make available the current authenticated connection if present. Will it help ?
