### ISSUE TITLE
password stored in session

### ISSUE THREAD

**Issue by mplx** [RiperFr/Security-ActiveDirectoryBundle#6]
Hi Loic,

I've noticed the user's password is stored permanently in the session in cleartext, which might not be the best thing.

As workaround we're overwriting the password from in an SecurityInteractiveLogin event, but this might arise some issues, i.e. breaking refreshUser() which seems to need the password.

```
public function onSecurityInteractiveLogin(InteractiveLoginEvent $event)
{
    if ($this->securityContext->isGranted('IS_AUTHENTICATED_FULLY')) {
        // user has just logged in
        // set the password to a random string like in the ZtecActiveDirectoryBundle
        $user = $event->getAuthenticationToken()->getUser()->setPassword(uniqid(true) . rand(0, 424242));
    }
```

In adUser.php you've done a function eraseCredentials() which could be suitable to remove the password from the session, but for now it's just empty.

If you wish I could post my workaround for merging, but I'd rather like to have an discussion on this issue and find a better solution.

What do you think?

**Comment by ztec** [comment]
Hi,

I agree with you. Storing the password in the session is not very good for security. 

First, two things : 
- Active directory does not allow anonymous connection (by default,and for 99% of installs) 
- I was not able to use an Administrative account to bypass the first point.

Using the credentials given by the user have two advantage : 
- It solve the anonymous connection problem.
- It use the authorizations of the user only (not administrator privileges).
  But as the login/pasword is required to connect the the AD with the user credential, I stored them directly in the session. 

The refreshUser method is used in some situation. I do not remember well when exactly.
If this method is broken, some situation may become unstable. If the password is not stored in the userEntity, when the method FetchData will be invoked, it will fail. 

If you have a solution to remove the password from session (or other storage) and do not breaking the refreshUser()/fetchData() methods, please explain and show, it would be very cool.

I have few Ideas that come in mind, but they need some time an test to be validated. I do not have this time right now.
- Storing the password in an encrypted way. It make the password unrecoverable if you do not have the key. For example if the Hack consist of stealing the SESSION only. Without the key, no password. But as the key will be available, if the attacker know the system, he will use the key.
- Storing all data of a user into a data cache. In this way, we can regenerate all user information without actually connect to the AD.
- Have a special treatment for people using an administrative account to connect to the AD. The administrative account can be used to fetchData() of a user in this case. 
- Any idea that might work ... 

Anyway, erasing the password like you did is dangerous and can lead to make the fetchData() method fail. An exceptions is thrown and lead to a 500. (The exceptions should be more specific at least to be cacheable , and not just \Exception :-) like I did (I open an issue))

What do you think ?

**Comment by mplx** [comment]
Hi Luic,

I've looked a bit further in the code and found that
- adUserProvider:::refreshUser() does not fetch new data, it just returns data from the $user object as $newuser and does not get any data from LDAP - in fact the current implementation could also do a simple return $user.
- adUserProvider:::fetchData() is only used in the authentification process (AdAuthProvider:::authenticate) where it has the the correct credentials from the TokenInterface.

This means the password does not need to be stored in the session as long as
- the app does not call fetchData() itself
- the app does not use adLDAP $adLdap itself

I don't know if these conditions are typically use cases, for the app I'm working on it's sufficient to just authenticate. So instead of the service listener from my original post which removes the password it's better not storing the password at all and use $token in fetchData() instead. Patch posted at https://gist.github.com/mplx/6069527

Otherwise if you intend keeping the password for some reason (ie. rewrite of refreshUser() with caching data and real updates with fetchData()) it should be encrypted. I'd have to dig into this more but out of the box I'm thinking of something like mcrypt()'ing the password in adUser and splitting the key between server and client (if client accepts cookies $key=$symfony_secret.$cookie else it's just the $symfony_secret; would require access to HttpFoundation\Request).

**Comment by ztec** [comment]
In this case, make the pull request. I will merge it after few tests. 

Thanks for your contribution.

**Comment by xelan** [comment]
Hi Luic,

after talking to mplx, I integrated the changes from the patch https://gist.github.com/mplx/6069527 and tested it over the last few days. I'll send you the pull request. Thanks!
